development:
  adapter: postgresql
  encoding: unicode
  database: robostoapi
  username: postgres
  password: 46mk9xa23&

test:
  adapter: postgresql
  encoding: unicode
  database: robostoapi
  pool: 5
  username: postgres
  password: 46mk9xa23&


Production:
  adapter: postgresql
  encoding: unicode
  database: robostoapi
  pool: 5
  username: postgres
  password: 46mk9xa23&
